version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.4.0
      - image: mongo:6.0.1-focal
    resource_class: large
    steps:
      - run: lsb-release -d
      - run:
          name: install MongoDB tools
          command: |
            # based on https://www.mongodb.com/docs/database-tools/installation/installation-linux/
            sudo dpkg -l mongodb-database-tools
